name: Statix Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    outputs:
      lint-success: ${{ steps.build-result.outputs.success }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@main

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Run statix linter
        run: |
          lintFlake() {
            if [ "$#" -ne 1 ]; then
              echo "Invalid number of arguments"
              exit 1
            fi

            echo "Linting $1 flake..."
            if nix run --extra-experimental-features 'nix-command flakes' nixpkgs#statix -- check "./$1"; then
              echo "success=true" >> $GITHUB_ENV
            else
              echo "Lint failed, listing $1 flake.lock for debugging:"
              cat ./$1/flake.lock
              echo "success=false" >> $GITHUB_ENV
              exit 1
            fi
          }

          lintFlake home-manager
          lintFlake system-config

      - name: Determine lint result
        id: build-result
        run: echo "success=${{ env.success }}" >> $GITHUB_OUTPUT
